### ISSUE TITLE
沒有連線到大會網路的報到畫面

### ISSUE THREAD

**Issue by Haraguroicha** [CPRTeam/CCIP-iOS#4]
需要顯示提示告知使用者需要連線到大會網路，並且不給使用 `報到` 功能

**Comment by FrankWu100** [comment]
0b95176a6a9f297e458febe8f3c0ab9c5c9c34c7

目前實作完 PopUp 方式的提示視窗, 以及補上該判斷的位置.
並且已修完 Blur PopUp 的 UI Issue.
接下來看是要用 Alert 還是 Blur PopUp 去呈現.
