### ISSUE TITLE
API Key leak

### ISSUE THREAD

**Issue by BirkhoffLee** [CPRTeam/CCIP-iOS#7]
https://github.com/CPRTeam/CCIP-iOS/blob/master/CCIP/CCIP/AppDelegate.m#L19

**Comment by denny0223** [comment]
Just app id, not token XD
https://github.com/CPRTeam/CCIP-iOS/blob/master/CCIP/CCIP/AppDelegate.m#L150

**Comment by Haraguroicha** [comment]
sorry, that naming was my fault...xDDD
